### ISSUE TITLE
allow source stdin

### ISSUE THREAD

**Issue by ygrek** [b0-system/b0caml#4]
for maximum mobility
```
b0caml <(curl -s https://raw.githubusercontent.com/ygrek/scraps/refs/heads/master/indente.ml)
/dev/fd/63: No such file or directory
(23) Failed writing body
```
(yes, we need `curl | sudo bash` for ocaml!)

**Comment by dbuenzli** [comment]
Note that part of the fix [lies](https://github.com/b0-system/b0/commit/245bd6f066c5ea0632177a162fc608d9f6a0f24e) in `b0` so you will have to update your pin on `b0`.
